
networks:
  net:
    driver: bridge

services:
  app:
    build:
      dockerfile: dockerfile
      context: .
      target: dev
    volumes:
      - type: bind
        source: .
        target: /app
    networks:
      - net
    environment:
      DB_DRIVER: postgres
      DB_HOST: db
      DB_USER: root
      DB_PASS: secret
      DB_NAME: quize
      DB_PORT: 5432
    depends_on:
      - db
    ports:
      - 3000:80

  db:
    image: postgres:11.1-alpine
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./volume/db:/var/lib/postgresql/data
    expose:
      - 5432:5432
    networks:
      - net

